spring:
  application:
    name: customer-server
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8080/eureka
  instance:
    hostname: localhost